workflows:
  ios-build:
    name: Build and Test iOS App
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: 16.2  # Assurez-vous que Xcode est installé et configuré
    scripts:
      - name: Install .NET SDK
        script: |
          # Télécharge et installe le .NET SDK
          curl -sSL https://aka.ms/install-dotnet.sh | bash
          dotnet --version  # Vérifie que .NET est installé correctement
      
      - name: Restore dependencies
        script: |
          dotnet restore SmartPharma5/SmartPharma5.csproj
      
      - name: Build iOS App
        script: |
          dotnet build SmartPharma5/SmartPharma5.csproj -f:net7.0-ios --configuration Release
      
      - name: Deploy to iOS Simulator
        script: |
          dotnet publish SmartPharma5/SmartPharma5.csproj -f:net7.0-ios --configuration Release -o ./output
          
          # Boot the iOS simulator (e.g., iPhone 14)
          xcrun simctl boot "iPhone 14"
          
          # Install the app on the simulator
          xcrun simctl install booted ./output/SmartPharma5.app
          
          # Launch the app on the simulator
          xcrun simctl launch booted com.tonentreprise.smartpharma  # Utilisez votre Bundle ID ici
    artifacts:
      - ./output/*
